### ISSUE TITLE
Python3 RTP Exception

### ISSUE THREAD

**Issue by haineb** [haineb/ASLHackfest#9]
hainesb@mobile4:~/hackfest/ASLHackfest$ ./apps/run_all.py 
Postmasters initializing. Ctrl-C to stop.
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/hainesb/.local/lib/python3.5/site-packages/asl_sdr_hackfest/postmaster.py", line 78, in run
    rtp_header = self.rtp_handler_tx.tx(srv['config']['ssrc'], 'gsm') # This is a byte array, not a header class
  File "/home/hainesb/.local/lib/python3.5/site-packages/asl_sdr_hackfest/protocols/rtp_handler.py", line 36, in tx
    return r.to_bytearray()
  File "/home/hainesb/.local/lib/python3.5/site-packages/asl_sdr_hackfest/protocols/protocol.py", line 49, in to_bytearray
    return bytearray(self.to_bitarray().bytes)
  File "/home/hainesb/.local/lib/python3.5/site-packages/asl_sdr_hackfest/protocols/rtp.py", line 57, in to_bitarray
    ba.append(self.bin_formater(self.timestamp, 32))
  File "/home/hainesb/.local/lib/python3.5/site-packages/asl_sdr_hackfest/protocols/protocol.py", line 30, in bin_formater
    return ("0b" + bin(value).lstrip('-0b').zfill(length))
TypeError: 'bytes' object cannot be interpreted as an integer

**Comment by haineb** [comment]
resolved
